spring:
  application:
    name: tlrj-api-gateway
  cloud:
    gateway:
      routes:
        - id: api-url
          uri: http://localhost:6677
          predicates:
            - Path=/api/**
server:
  port: 8848
dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-register
    address: nacos://192.168.66.128:8848